{
	"version": 1643753839,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/pipe.png",
		"images/tiledbackground14.png",
		"images/pedraa.png",
		"images/chao.png",
		"images/moving_platform.png",
		"images/chaoug.png",
		"images/pedraug.png",
		"images/moeda-sheet0.png",
		"images/moeda-sheet1.png",
		"images/moeda-sheet2.png",
		"images/flag-sheet0.png",
		"images/bandeira-sheet0.png",
		"images/cgc-sheet0.png",
		"images/cgb-sheet0.png",
		"images/cbb34.png",
		"images/gelo.png",
		"images/mario-sheet0.png",
		"images/bg11.png",
		"images/bgmenu.png",
		"images/tiledbackground15.png",
		"images/bggelo.png",
		"images/tiledbackground18.png",
		"images/tiledbackground19.png",
		"images/tiledbackground24.png",
		"images/logosmb-sheet0.png",
		"images/texto1.png",
		"images/texto2.png",
		"images/tiledbackground6.png",
		"images/tiledbackground7.png",
		"images/tiledbackground8.png",
		"images/tiledbackground11.png",
		"images/tiledbackground20.png",
		"images/tiledbackground21.png",
		"images/tiledbackground22.png",
		"images/particles.png",
		"images/tiledbackground23.png",
		"images/tiledbackground25.png",
		"media/smb_overworld.ogg",
		"media/yt1s.com - athletic theme 8 bit chain link charge super mario 3d world (online-audio-converter.com).ogg",
		"media/yt1s.com - super mario 3d land snow overworld 8 bit (online-audio-converter.com).ogg",
		"media/new super mario bros 2 - forest theme 8bit (online-audio-converter.com).ogg",
		"media/yt1s.com - super mario bros 3 underworld theme (online-audio-converter.com).ogg",
		"media/overworld_8_bit_-_super_mario_3d_land (online-audio-converter.com).ogg",
		"media/yt1s.com - super mario 3d land title screen 8bit (online-audio-converter.com).ogg",
		"media/yt1s.com - conkdor canyon 8bit cover super mario 3d world_64kbps (online-audio-converter.com).ogg",
		"media/yt1s.com - 8bit beach theme super mario 3d land_64kbps (online-audio-converter.com).ogg",
		"media/smb_coin.ogg",
		"media/smb_jump-small.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}